export const entranceExams = [
    {
        id: 1,
        name: "JEE Main",
        fullName: "Joint Entrance Examination - Main",
        description: "The gateway to NITs, IIITs, and other Centrally Funded Technical Institutions (CFTIs), as well as the preliminary exam for JEE Advanced.",
        website: "https://jeemain.nta.ac.in/",
        tentativeDate: "Session 1: Jan / Session 2: Apr",
    },
    {
        id: 2,
        name: "JEE Advanced",
        fullName: "Joint Entrance Examination - Advanced",
        description: "Conducted by the seven Zonal Coordinating IITs. It is the sole prerequisite for admission to the Indian Institutes of Technology (IITs).",
        website: "https://jeeadv.ac.in/",
        tentativeDate: "May / June",
    },
    {
        id: 3,
        name: "BITSAT",
        fullName: "Birla Institute of Technology and Science Admission Test",
        description: "Computer-based online test for admission to Integrated First Degree Programmes of BITS Pilani Campuses in Pilani, Goa, and Hyderabad.",
        website: "https://www.bitsadmission.com/",
        tentativeDate: "May / June",
    },
    {
        id: 4,
        name: "VITEEE",
        fullName: "VIT Engineering Entrance Examination",
        description: "Conducted by Vellore Institute of Technology for admission to its B.Tech programmes in Vellore, Chennai, AP, and Bhopal.",
        website: "https://viteee.vit.ac.in/",
        tentativeDate: "April",
    },
    {
        id: 5,
        name: "WBJEE",
        fullName: "West Bengal Joint Entrance Examination",
        description: "State-level exam for admission to undergraduate courses in Engineering & Technology, Pharmacy and Architecture in West Bengal.",
        website: "https://wbjeeb.nic.in/",
        tentativeDate: "April",
    },
    {
        id: 6,
        name: "MHT CET",
        fullName: "Maharashtra Common Entrance Test",
        description: "State-level entrance exam for admission to engineering and pharmacy courses in various colleges in Maharashtra.",
        website: "https://cetcell.mahacet.org/",
        tentativeDate: "May",
    },
    {
        id: 7,
        name: "COMEDK UGET",
        fullName: "Consortium of Medical, Engineering and Dental Colleges of Karnataka",
        description: "State-level exam for admission to engineering courses in member institutions in Karnataka.",
        website: "https://www.comedk.org/",
        tentativeDate: "May",
    },
    {
        id: 8,
        name: "KCET",
        fullName: "Karnataka Common Entrance Test",
        description: "Conducted by KEA for admission to professional courses in Karnataka.",
        website: "https://cetonline.karnataka.gov.in/kea/",
        tentativeDate: "April",
    },
    {
        id: 9,
        name: "SRMJEEE",
        fullName: "SRM Joint Engineering Entrance Examination",
        description: "Entrance exam for admission to B.Tech programmes offered in SRM Institute of Science and Technology campuses.",
        website: "https://www.srmist.edu.in/",
        tentativeDate: "April / June / July (Multiple Phases)",
    },
    {
        id: 10,
        name: "MET",
        fullName: "Manipal Entrance Test",
        description: "conducted by Manipal Academy of Higher Education (MAHE) for admission to various courses including B.Tech.",
        website: "https://manipal.edu/",
        tentativeDate: "April / May",
    },
];

export const topColleges = [
    // IITs - JEE Advanced (23 Total)
    { id: 1, name: "Indian Institute of Technology (IIT) Madras", website: "https://www.iitm.ac.in/", location: "Chennai, Tamil Nadu", exam: "JEE Advanced" },
    { id: 2, name: "Indian Institute of Technology (IIT) Delhi", website: "https://home.iitd.ac.in/", location: "New Delhi, Delhi", exam: "JEE Advanced" },
    { id: 3, name: "Indian Institute of Technology (IIT) Bombay", website: "https://www.iitb.ac.in/", location: "Mumbai, Maharashtra", exam: "JEE Advanced" },
    { id: 4, name: "Indian Institute of Technology (IIT) Kanpur", website: "https://www.iitk.ac.in/", location: "Kanpur, Uttar Pradesh", exam: "JEE Advanced" },
    { id: 5, name: "Indian Institute of Technology (IIT) Kharagpur", website: "http://www.iitkgp.ac.in/", location: "Kharagpur, West Bengal", exam: "JEE Advanced" },
    { id: 6, name: "Indian Institute of Technology (IIT) Roorkee", website: "https://www.iitr.ac.in/", location: "Roorkee, Uttarakhand", exam: "JEE Advanced" },
    { id: 7, name: "Indian Institute of Technology (IIT) Guwahati", website: "https://www.iitg.ac.in/", location: "Guwahati, Assam", exam: "JEE Advanced" },
    { id: 8, name: "Indian Institute of Technology (IIT) Hyderabad", website: "https://www.iith.ac.in/", location: "Hyderabad, Telangana", exam: "JEE Advanced" },
    { id: 9, name: "Indian Institute of Technology (IIT) BHU Varanasi", website: "https://www.iitbhu.ac.in/", location: "Varanasi, Uttar Pradesh", exam: "JEE Advanced" },
    { id: 10, name: "Indian Institute of Technology (IIT) Indore", website: "https://www.iiti.ac.in/", location: "Indore, Madhya Pradesh", exam: "JEE Advanced" },
    { id: 11, name: "Indian Institute of Technology (IIT) Dhanbad (ISM)", website: "https://www.iitism.ac.in/", location: "Dhanbad, Jharkhand", exam: "JEE Advanced" },
    { id: 12, name: "Indian Institute of Technology (IIT) Gandhinagar", website: "https://www.iitgn.ac.in/", location: "Gandhinagar, Gujarat", exam: "JEE Advanced" },
    { id: 13, name: "Indian Institute of Technology (IIT) Ropar", website: "https://www.iitrpr.ac.in/", location: "Ropar, Punjab", exam: "JEE Advanced" },
    { id: 14, name: "Indian Institute of Technology (IIT) Patna", website: "https://www.iitp.ac.in/", location: "Patna, Bihar", exam: "JEE Advanced" },
    { id: 15, name: "Indian Institute of Technology (IIT) Bhubaneswar", website: "https://www.iitbbs.ac.in/", location: "Bhubaneswar, Odisha", exam: "JEE Advanced" },
    { id: 16, name: "Indian Institute of Technology (IIT) Jodhpur", website: "https://iitj.ac.in/", location: "Jodhpur, Rajasthan", exam: "JEE Advanced" },
    { id: 17, name: "Indian Institute of Technology (IIT) Mandi", website: "https://www.iitmandi.ac.in/", location: "Mandi, Himachal Pradesh", exam: "JEE Advanced" },
    { id: 18, name: "Indian Institute of Technology (IIT) Tirupati", website: "https://iittp.ac.in/", location: "Tirupati, Andhra Pradesh", exam: "JEE Advanced" },
    { id: 19, name: "Indian Institute of Technology (IIT) Palakkad", website: "https://iitpkd.ac.in/", location: "Palakkad, Kerala", exam: "JEE Advanced" },
    { id: 20, name: "Indian Institute of Technology (IIT) Jammu", website: "https://iitjammu.ac.in/", location: "Jammu, J&K", exam: "JEE Advanced" },
    { id: 21, name: "Indian Institute of Technology (IIT) Dharwad", website: "https://www.iitdh.ac.in/", location: "Dharwad, Karnataka", exam: "JEE Advanced" },
    { id: 22, name: "Indian Institute of Technology (IIT) Bhilai", website: "https://www.iitbhilai.ac.in/", location: "Bhilai, Chhattisgarh", exam: "JEE Advanced" },
    { id: 23, name: "Indian Institute of Technology (IIT) Goa", website: "https://www.iitgoa.ac.in/", location: "Ponda, Goa", exam: "JEE Advanced" },

    // NITs - JEE Main (31 Total)
    { id: 24, name: "National Institute of Technology (NIT) Tiruchirappalli", website: "https://www.nitt.edu/", location: "Tiruchirappalli, Tamil Nadu", exam: "JEE Main" },
    { id: 25, name: "National Institute of Technology (NIT) Karnataka, Surathkal", website: "https://www.nitk.ac.in/", location: "Surathkal, Karnataka", exam: "JEE Main" },
    { id: 26, name: "National Institute of Technology (NIT) Rourkela", website: "https://www.nitrkl.ac.in/", location: "Rourkela, Odisha", exam: "JEE Main" },
    { id: 27, name: "National Institute of Technology (NIT) Warangal", website: "https://www.nitw.ac.in/", location: "Warangal, Telangana", exam: "JEE Main" },
    { id: 28, name: "National Institute of Technology (NIT) Calicut", website: "http://www.nitc.ac.in/", location: "Calicut, Kerala", exam: "JEE Main" },
    { id: 29, name: "Malaviya National Institute of Technology (MNIT)", website: "http://www.mnit.ac.in/", location: "Jaipur, Rajasthan", exam: "JEE Main" },
    { id: 30, name: "Visvesvaraya National Institute of Technology (VNIT)", website: "https://vnit.ac.in/", location: "Nagpur, Maharashtra", exam: "JEE Main" },
    { id: 31, name: "National Institute of Technology (NIT) Silchar", website: "http://www.nits.ac.in/", location: "Silchar, Assam", exam: "JEE Main" },
    { id: 32, name: "National Institute of Technology (NIT) Durgapur", website: "https://nitdgp.ac.in/", location: "Durgapur, West Bengal", exam: "JEE Main" },
    { id: 33, name: "National Institute of Technology (NIT) Delhi", website: "https://nitdelhi.ac.in/", location: "New Delhi, Delhi", exam: "JEE Main" },
    { id: 34, name: "Motilal Nehru National Institute of Technology (MNNIT) Allahabad", website: "http://www.mnnit.ac.in/", location: "Prayagraj, Uttar Pradesh", exam: "JEE Main" },
    { id: 35, name: "National Institute of Technology (NIT) Kurukshetra", website: "https://nitkkr.ac.in/", location: "Kurukshetra, Haryana", exam: "JEE Main" },
    { id: 36, name: "National Institute of Technology (NIT) Raipur", website: "http://www.nitrr.ac.in/", location: "Raipur, Chhattisgarh", exam: "JEE Main" },
    { id: 37, name: "Sardar Vallabhbhai National Institute of Technology (SVNIT)", website: "https://www.svnit.ac.in/", location: "Surat, Gujarat", exam: "JEE Main" },
    { id: 38, name: "National Institute of Technology (NIT) Meghalaya", website: "http://nitm.ac.in/", location: "Shillong, Meghalaya", exam: "JEE Main" },
    { id: 39, name: "National Institute of Technology (NIT) Agartala", website: "https://www.nita.ac.in/", location: "Agartala, Tripura", exam: "JEE Main" },
    { id: 40, name: "National Institute of Technology (NIT) Hamirpur", website: "https://nith.ac.in/", location: "Hamirpur, Himachal Pradesh", exam: "JEE Main" },
    { id: 41, name: "Maulana Azad National Institute of Technology (MANIT)", website: "http://www.manit.ac.in/", location: "Bhopal, Madhya Pradesh", exam: "JEE Main" },
    { id: 42, name: "National Institute of Technology (NIT) Goa", website: "https://www.nitgoa.ac.in/", location: "Ponda, Goa", exam: "JEE Main" },
    { id: 43, name: "National Institute of Technology (NIT) Jamshedpur", website: "http://www.nitjsr.ac.in/", location: "Jamshedpur, Jharkhand", exam: "JEE Main" },
    { id: 44, name: "National Institute of Technology (NIT) Patna", website: "http://www.nitp.ac.in/", location: "Patna, Bihar", exam: "JEE Main" },
    { id: 45, name: "Dr. B. R. Ambedkar National Institute of Technology (NIT) Jalandhar", website: "https://www.nitj.ac.in/", location: "Jalandhar, Punjab", exam: "JEE Main" },
    { id: 46, name: "National Institute of Technology (NIT) Manipur", website: "http://www.nitmanipur.ac.in/", location: "Imphal, Manipur", exam: "JEE Main" },
    { id: 47, name: "National Institute of Technology (NIT) Puducherry", website: "https://www.nitpy.ac.in/", location: "Karaikal, Puducherry", exam: "JEE Main" },
    { id: 48, name: "National Institute of Technology (NIT) Sikkim", website: "https://nitsikkim.ac.in/", location: "Ravangla, Sikkim", exam: "JEE Main" },
    { id: 49, name: "National Institute of Technology (NIT) Arunachal Pradesh", website: "https://www.nitap.ac.in/", location: "Yupia, Arunachal Pradesh", exam: "JEE Main" },
    { id: 50, name: "National Institute of Technology (NIT) Uttarakhand", website: "https://nituk.ac.in/", location: "Srinagar, Uttarakhand", exam: "JEE Main" },
    { id: 51, name: "National Institute of Technology (NIT) Mizoram", website: "https://nitmz.ac.in/", location: "Aizawl, Mizoram", exam: "JEE Main" },
    { id: 52, name: "National Institute of Technology (NIT) Nagaland", website: "https://nitnagaland.ac.in/", location: "Dimapur, Nagaland", exam: "JEE Main" },
    { id: 53, name: "National Institute of Technology (NIT) Andhra Pradesh", website: "https://nitandhra.ac.in/", location: "Tadepalligudem, Andhra Pradesh", exam: "JEE Main" },
    { id: 54, name: "National Institute of Technology (NIT) Srinagar", website: "https://nitsri.ac.in/", location: "Srinagar, J&K", exam: "JEE Main" },

    // IIITs (Triple ITs) - JEE Main (Usually)
    { id: 55, name: "International Institute of Information Technology (IIIT) Hyderabad", website: "https://www.iiit.ac.in/", location: "Hyderabad, Telangana", exam: "JEE Main / UGEE" },
    { id: 56, name: "Indraprastha Institute of Information Technology (IIIT) Delhi", website: "https://www.iiitd.ac.in/", location: "New Delhi, Delhi", exam: "JEE Main (JAC)" },
    { id: 57, name: "Indian Institute of Information Technology (IIIT) Allahabad", website: "https://www.iiita.ac.in/", location: "Prayagraj, Uttar Pradesh", exam: "JEE Main" },
    { id: 58, name: "Indian Institute of Information Technology (IIIT) Bangalore", website: "https://www.iiitb.ac.in/", location: "Bangalore, Karnataka", exam: "JEE Main" },
    { id: 59, name: "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)", website: "https://www.daiict.ac.in/", location: "Gandhinagar, Gujarat", exam: "JEE Main" },
    { id: 60, name: "Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Jabalpur", website: "https://www.iiitdmj.ac.in/", location: "Jabalpur, Madhya Pradesh", exam: "JEE Main" },
    { id: 61, name: "ABV-Indian Institute of Information Technology and Management (IIITM) Gwalior", website: "https://www.iiitm.ac.in/", location: "Gwalior, Madhya Pradesh", exam: "JEE Main" },
    { id: 62, name: "Indian Institute of Information TechnologyDM (IIITDM) Kancheepuram", website: "https://www.iiitdm.ac.in/", location: "Chennai, Tamil Nadu", exam: "JEE Main" },
    { id: 63, name: "Indian Institute of Information Technology (IIIT) Guwahati", website: "https://www.iiitg.ac.in/", location: "Guwahati, Assam", exam: "JEE Main" },
    { id: 64, name: "Indian Institute of Information Technology (IIIT) Vadodara", website: "http://iiitvadodara.ac.in/", location: "Gandhinagar, Gujarat", exam: "JEE Main" },
    { id: 65, name: "Indian Institute of Information Technology (IIIT) Kota", website: "https://www.iiitkota.ac.in/", location: "Kota, Rajasthan", exam: "JEE Main" },
    { id: 66, name: "Indian Institute of Information Technology (IIIT) Tiruchirappalli", website: "https://www.iiitt.ac.in/", location: "Tiruchirappalli, Tamil Nadu", exam: "JEE Main" },
    { id: 67, name: "Indian Institute of Information Technology (IIIT) Srirangam", website: "http://www.iiitt.ac.in/", location: "Tiruchirappalli, Tamil Nadu", exam: "JEE Main" },
    { id: 68, name: "Indian Institute of Information Technology (IIIT) Lucknow", website: "https://iiitl.ac.in/", location: "Lucknow, Uttar Pradesh", exam: "JEE Main" },
    { id: 69, name: "Indian Institute of Information Technology (IIIT) Pune", website: "https://www.iiitp.ac.in/", location: "Pune, Maharashtra", exam: "JEE Main" },
    { id: 70, name: "Indian Institute of Information Technology (IIIT) Bhopal", website: "https://iiitbhopal.ac.in/", location: "Bhopal, Madhya Pradesh", exam: "JEE Main" },
    { id: 71, name: "Indian Institute of Information Technology (IIIT) Surat", website: "http://www.iiitsurat.ac.in/", location: "Surat, Gujarat", exam: "JEE Main" },
    { id: 72, name: "Indian Institute of Information Technology (IIIT) Kottayam", website: "https://www.iiitkottayam.ac.in/", location: "Kottayam, Kerala", exam: "JEE Main" },
    { id: 73, name: "Indian Institute of Information Technology (IIIT) Ranchi", website: "https://iiitranchi.ac.in/", location: "Ranchi, Jharkhand", exam: "JEE Main" },
    { id: 74, name: "Indian Institute of Information Technology (IIIT) Nagpur", website: "https://iiitn.ac.in/", location: "Nagpur, Maharashtra", exam: "JEE Main" },
    { id: 75, name: "Indian Institute of Information Technology (IIIT) Una", website: "https://iiitu.ac.in/", location: "Una, Himachal Pradesh", exam: "JEE Main" },
    { id: 76, name: "Indian Institute of Information Technology (IIIT) Bhagalpur", website: "https://iiitbh.ac.in/", location: "Bhagalpur, Bihar", exam: "JEE Main" },
    { id: 77, name: "Indian Institute of Information Technology (IIIT) Kalyani", website: "https://iiitkalyani.ac.in/", location: "Kalyani, West Bengal", exam: "JEE Main" },
    { id: 78, name: "Indian Institute of Information Technology (IIIT) Dharwad", website: "https://iiitdwd.ac.in/", location: "Dharwad, Karnataka", exam: "JEE Main" },
    { id: 79, name: "Indian Institute of Information Technology (IIIT) Kurnool", website: "https://iiitk.ac.in/", location: "Kurnool, Andhra Pradesh", exam: "JEE Main" },
    { id: 80, name: "Indian Institute of Information Technology (IIIT) Raichur", website: "https://www.iiitr.ac.in/", location: "Raichur, Karnataka", exam: "JEE Main" },

    // BITS
    { id: 81, name: "Birla Institute of Technology & Science (BITS) Pilani", website: "https://www.bits-pilani.ac.in/", location: "Pilani, Rajasthan", exam: "BITSAT" },
    { id: 82, name: "BITS Pilani - Goa Campus", website: "https://www.bits-pilani.ac.in/goa/", location: "Zuarinagar, Goa", exam: "BITSAT" },
    { id: 83, name: "BITS Pilani - Hyderabad Campus", website: "https://www.bits-pilani.ac.in/hyderabad/", location: "Hyderabad, Telangana", exam: "BITSAT" },

    // VIT
    { id: 84, name: "Vellore Institute of Technology (VIT)", website: "https://vit.ac.in/", location: "Vellore, Tamil Nadu", exam: "VITEEE" },
    { id: 85, name: "VIT Chennai", website: "https://chennai.vit.ac.in/", location: "Chennai, Tamil Nadu", exam: "VITEEE" },
    { id: 86, name: "VIT-AP University", website: "https://vitap.ac.in/", location: "Amaravati, Andhra Pradesh", exam: "VITEEE" },
    { id: 87, name: "VIT Bhopal", website: "https://vitbhopal.ac.in/", location: "Bhopal, Madhya Pradesh", exam: "VITEEE" },

    // Top Private / Deemed / State Govt
    { id: 88, name: "Jadavpur University", website: "http://www.jaduniv.edu.in/", location: "Kolkata, West Bengal", exam: "WBJEE" },
    { id: 89, name: "Anna University (CEG Guindy)", website: "https://ceg.annauniv.edu/", location: "Chennai, Tamil Nadu", exam: "TNEA" },
    { id: 90, name: "Madras Institute of Technology (MIT)", website: "https://mitindia.edu/", location: "Chennai, Tamil Nadu", exam: "TNEA" },
    { id: 91, name: "Delhi Technological University (DTU)", website: "http://www.dtu.ac.in/", location: "New Delhi, Delhi", exam: "JEE Main (JAC)" },
    { id: 92, name: "Netaji Subhas University of Technology (NSUT)", website: "http://nsut.ac.in/", location: "New Delhi, Delhi", exam: "JEE Main (JAC)" },
    { id: 93, name: "Thapar Institute of Engineering and Technology", website: "https://www.thapar.edu/", location: "Patiala, Punjab", exam: "JEE Main / Class 12" },
    { id: 94, name: "Amrita Vishwa Vidyapeetham", website: "https://www.amrita.edu/", location: "Coimbatore, Tamil Nadu", exam: "AEEE / JEE Main" },
    { id: 95, name: "Manipal Institute of Technology (MIT)", website: "https://manipal.edu/mit.html", location: "Manipal, Karnataka", exam: "MET" },
    { id: 96, name: "S.R.M. Institute of Science and Technology", website: "https://www.srmist.edu.in/", location: "Chennai, Tamil Nadu", exam: "SRMJEEE" },
    { id: 97, name: "Institute of Chemical Technology (ICT)", website: "https://www.ictmumbai.edu.in/", location: "Mumbai, Maharashtra", exam: "MHT CET / JEE Main" },
    { id: 98, name: "College of Engineering, Pune (COEP)", website: "https://www.coep.org.in/", location: "Pune, Maharashtra", exam: "MHT CET / JEE Main" },
    { id: 99, name: "Veermata Jijabai Technological Institute (VJTI)", website: "https://www.vjti.ac.in/", location: "Mumbai, Maharashtra", exam: "MHT CET / JEE Main" },
    { id: 100, name: "Birla Institute of Technology (BIT) Mesra", website: "https://www.bitmesra.ac.in/", location: "Ranchi, Jharkhand", exam: "JEE Main" },

    // 101-150
    { id: 101, name: "RV College of Engineering", website: "https://www.rvce.edu.in/", location: "Bangalore, Karnataka", exam: "KCET / COMEDK" },
    { id: 102, name: "B.M.S. College of Engineering", website: "https://www.bmsce.ac.in/", location: "Bangalore, Karnataka", exam: "KCET / COMEDK" },
    { id: 103, name: "MS Ramaiah Institute of Technology", website: "https://www.msrit.edu/", location: "Bangalore, Karnataka", exam: "KCET / COMEDK" },
    { id: 104, name: "PES University", website: "https://pes.edu/", location: "Bangalore, Karnataka", exam: "PESSAT / KCET" },
    { id: 105, name: "Sri Sivasubramaniya Nadar College of Engineering (SSN)", website: "https://www.ssn.edu.in/", location: "Chennai, Tamil Nadu", exam: "TNEA" },
    { id: 106, name: "Coimbatore Institute of Technology (CIT)", website: "https://www.cit.edu.in/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 107, name: "PSG College of Technology", website: "https://www.psgtech.edu/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 108, name: "Thiagarajar College of Engineering", website: "https://www.tce.edu/", location: "Madurai, Tamil Nadu", exam: "TNEA" },
    { id: 109, name: "Sathyabama Institute of Science and Technology", website: "https://www.sathyabama.ac.in/", location: "Chennai, Tamil Nadu", exam: "SAEEE" },
    { id: 110, name: "Kalinga Institute of Industrial Technology (KIIT)", website: "https://kiit.ac.in/", location: "Bhubaneswar, Odisha", exam: "KIITEE" },
    { id: 111, name: "Siksha 'O' Anusandhan (SOA)", website: "https://www.soa.ac.in/", location: "Bhubaneswar, Odisha", exam: "SAAT" },
    { id: 112, name: "Jamia Millia Islamia", website: "https://www.jmi.ac.in/", location: "New Delhi, Delhi", exam: "JEE Main" },
    { id: 113, name: "Aligarh Muslim University (AMU)", website: "https://www.amu.ac.in/", location: "Aligarh, Uttar Pradesh", exam: "AMUEEE" },
    { id: 114, name: "Lovely Professional University (LPU)", website: "https://www.lpu.in/", location: "Phagwara, Punjab", exam: "LPUNEST" },
    { id: 115, name: "Chandigarh University", website: "https://www.cuchd.in/", location: "Mohali, Punjab", exam: "CUCET" },
    { id: 116, name: "Amity University", website: "https://www.amity.edu/", location: "Noida, Uttar Pradesh", exam: "Amity JEE" },
    { id: 117, name: "Shiv Nadar University", website: "https://snu.edu.in/", location: "Greater Noida, Uttar Pradesh", exam: "SNUSAT" },
    { id: 118, name: "Jaypee Institute of Information Technology (JIIT)", website: "https://www.jiit.ac.in/", location: "Noida, Uttar Pradesh", exam: "JEE Main" },
    { id: 119, name: "Galgotias University", website: "https://www.galgotiasuniversity.edu.in/", location: "Greater Noida, Uttar Pradesh", exam: "GEEE" },
    { id: 120, name: "Kumaraguru College of Technology", website: "https://www.kct.ac.in/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 121, name: "Rajalakshmi Engineering College", website: "https://www.rajalakshmi.org/", location: "Chennai, Tamil Nadu", exam: "TNEA" },
    { id: 122, name: "Sri Krishna College of Engineering and Technology", website: "https://www.skcet.ac.in/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 123, name: "Nirma University", website: "https://nirmauni.ac.in/", location: "Ahmedabad, Gujarat", exam: "JEE Main" },
    { id: 124, name: "Pandit Deendayal Energy University (PDEU)", website: "https://www.pdpu.ac.in/", location: "Gandhinagar, Gujarat", exam: "JEE Main" },
    { id: 125, name: "Vishwakarma Institute of Technology (VIT Pune)", website: "https://www.vit.edu/", location: "Pune, Maharashtra", exam: "MHT CET" },
    { id: 126, name: "MIT World Peace University (MIT-WPU)", website: "https://mitwpu.edu.in/", location: "Pune, Maharashtra", exam: "MHT CET" },
    { id: 127, name: "Symbiosis Institute of Technology", website: "https://www.sitpune.edu.in/", location: "Pune, Maharashtra", exam: "SITEEE" },
    { id: 128, name: "Walchand College of Engineering", website: "http://www.walchandsangli.ac.in/", location: "Sangli, Maharashtra", exam: "MHT CET" },
    { id: 129, name: "Sardar Patel College of Engineering (SPCE)", website: "https://www.spce.ac.in/", location: "Mumbai, Maharashtra", exam: "MHT CET" },
    { id: 130, name: "Harcourt Butler Technical University (HBTU)", website: "https://hbtu.ac.in/", location: "Kanpur, Uttar Pradesh", exam: "JEE Main" },
    { id: 131, name: "Institute of Engineering and Technology (IET) Lucknow", website: "https://ietlucknow.ac.in/", location: "Lucknow, Uttar Pradesh", exam: "UPCET" },
    { id: 132, name: "Madan Mohan Malaviya University of Technology (MMMUT)", website: "http://www.mmmut.ac.in/", location: "Gorakhpur, Uttar Pradesh", exam: "JEE Main" },
    { id: 133, name: "Guru Gobind Singh Indraprastha University (GGSIPU)", website: "http://www.ipu.ac.in/", location: "New Delhi, Delhi", exam: "IPU CET" },
    { id: 134, name: "University of Petroleum and Energy Studies (UPES)", website: "https://www.upes.ac.in/", location: "Dehradun, Uttarakhand", exam: "UPESEAT" },
    { id: 135, name: "Graphic Era University", website: "https://www.geu.ac.in/", location: "Dehradun, Uttarakhand", exam: "JEE Main" },
    { id: 136, name: "Hindustan Institute of Technology and Science (HITS)", website: "https://hindustanuniv.ac.in/", location: "Chennai, Tamil Nadu", exam: "HITSEEE" },
    { id: 137, name: "Kalasalingam Academy of Research and Education", website: "https://kalasalingam.ac.in/", location: "Krishnankoil, Tamil Nadu", exam: "KUEE" },
    { id: 138, name: "Shanmugha Arts Science Technology & Research Academy (SASTRA)", website: "https://www.sastra.edu/", location: "Thanjavur, Tamil Nadu", exam: "JEE Main / Class 12" },
    { id: 139, name: "Punjab Engineering College (PEC)", website: "https://pec.ac.in/", location: "Chandigarh", exam: "JEE Main" },
    { id: 140, name: "Bangalore Institute of Technology", website: "https://bit-bangalore.edu.in/", location: "Bangalore, Karnataka", exam: "KCET / COMEDK" },
    { id: 141, name: "Nitte Meenakshi Institute of Technology", website: "https://www.nmit.ac.in/", location: "Bangalore, Karnataka", exam: "KCET" },
    { id: 142, name: "Dayananda Sagar College of Engineering", website: "https://www.dsce.edu.in/", location: "Bangalore, Karnataka", exam: "KCET / COMEDK" },
    { id: 143, name: "Sir M Visvesvaraya Institute of Technology", website: "https://www.sirmvit.edu/", location: "Bangalore, Karnataka", exam: "KCET" },
    { id: 144, name: "SJB Institute of Technology", website: "https://www.sjbit.edu.in/", location: "Bangalore, Karnataka", exam: "KCET" },
    { id: 145, name: "New Horizon College of Engineering", website: "https://newhorizonindia.edu/nhengineering/", location: "Bangalore, Karnataka", exam: "KCET" },
    { id: 146, name: "JSS Science and Technology University", website: "https://jssstuniv.in/", location: "Mysore, Karnataka", exam: "KCET" },
    { id: 147, name: "The National Institute of Engineering", website: "https://nie.ac.in/", location: "Mysore, Karnataka", exam: "KCET" },
    { id: 148, name: "Siddaganga Institute of Technology", website: "http://www.sit.ac.in/", location: "Tumkur, Karnataka", exam: "KCET" },
    { id: 149, name: "NMAM Institute of Technology", website: "https://nmamit.nitte.edu.in/", location: "Karkala, Karnataka", exam: "NUCAT" },
    { id: 150, name: "Manipal University Jaipur", website: "https://jaipur.manipal.edu/", location: "Jaipur, Rajasthan", exam: "MET / JEE Main" },

    // 151-200
    { id: 151, name: "Srm University, AP", website: "https://srmap.edu.in/", location: "Amaravati, Andhra Pradesh", exam: "SRMJEEE" },
    { id: 152, name: "Mahindra University", website: "https://www.mahindrauniversity.edu.in/", location: "Hyderabad, Telangana", exam: "JEE Main" },
    { id: 153, name: "Chaitanya Bharathi Institute of Technology (CBIT)", website: "https://www.cbit.ac.in/", location: "Hyderabad, Telangana", exam: "EAMCET" },
    { id: 154, name: "VNR Vignana Jyothi Institute of Engineering and Technology", website: "http://www.vnrvjiet.ac.in/", location: "Hyderabad, Telangana", exam: "EAMCET" },
    { id: 155, name: "Vasavi College of Engineering", website: "https://www.vce.ac.in/", location: "Hyderabad, Telangana", exam: "EAMCET" },
    { id: 156, name: "Gokaraju Rangaraju Institute of Engineering and Technology", website: "http://www.griet.ac.in/", location: "Hyderabad, Telangana", exam: "EAMCET" },
    { id: 157, name: "Gayatri Vidya Parishad College of Engineering", website: "http://www.gvpce.ac.in/", location: "Visakhapatnam, Andhra Pradesh", exam: "AP EAMCET" },
    { id: 158, name: "R.V.R. & J.C. College of Engineering", website: "http://rvrjcce.ac.in/", location: "Guntur, Andhra Pradesh", exam: "AP EAMCET" },
    { id: 159, name: "Vignan's Foundation for Science, Technology & Research", website: "https://www.vignan.ac.in/", location: "Guntur, Andhra Pradesh", exam: "VSAT" },
    { id: 160, name: "KLE Technological University", website: "https://kletech.ac.in/", location: "Hubli, Karnataka", exam: "KCET" },
    { id: 161, name: "GITAM Deemed University", website: "https://www.gitam.edu/", location: "Visakhapatnam, Andhra Pradesh", exam: "GAT" },
    { id: 162, name: "Koneru Lakshmaiah Education Foundation (KL University)", website: "https://www.kluniversity.in/", location: "Guntur, Andhra Pradesh", exam: "KLEEE" },
    { id: 163, name: "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology", website: "https://www.veltech.edu.in/", location: "Chennai, Tamil Nadu", exam: "VTUEEE" },
    { id: 164, name: "Karunya Institute of Technology and Sciences", website: "https://www.karunya.edu/", location: "Coimbatore, Tamil Nadu", exam: "KEE" },
    { id: 165, name: "B.S. Abdur Rahman Crescent Institute of Science and Technology", website: "https://crescent.education/", location: "Chennai, Tamil Nadu", exam: "CIEAT" },
    { id: 166, name: "Bannari Amman Institute of Technology", website: "https://www.bitsathy.ac.in/", location: "Sathyamangalam, Tamil Nadu", exam: "TNEA" },
    { id: 167, name: "Kongu Engineering College", website: "https://www.kongu.ac.in/", location: "Erode, Tamil Nadu", exam: "TNEA" },
    { id: 168, name: "Sri Krishna College of Technology", website: "http://www.skct.edu.in/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 169, name: "Mepco Schlenk Engineering College", website: "https://www.mepcoeng.ac.in/", location: "Sivakasi, Tamil Nadu", exam: "TNEA" },
    { id: 170, name: "Government College of Technology, Coimbatore", website: "https://gct.ac.in/", location: "Coimbatore, Tamil Nadu", exam: "TNEA" },
    { id: 171, name: "Government College of Engineering, Salem", website: "https://gcesalem.edu.in/", location: "Salem, Tamil Nadu", exam: "TNEA" },
    { id: 172, name: "Alagappa Chettiar Government College of Engineering and Technology", website: "https://accet.edu.in/", location: "Karaikudi, Tamil Nadu", exam: "TNEA" },
    { id: 173, name: "Vishwakarma Institute of Information Technology (VIIT)", website: "https://www.viit.ac.in/", location: "Pune, Maharashtra", exam: "MHT CET" },
    { id: 174, name: "Pimpri Chinchwad College of Engineering (PCCOE)", website: "http://www.pccoepune.com/", location: "Pune, Maharashtra", exam: "MHT CET" },
    { id: 175, name: "Dwarkadas J. Sanghvi College of Engineering", website: "https://www.djsce.ac.in/", location: "Mumbai, Maharashtra", exam: "MHT CET" },
    { id: 176, name: "Thadomal Shahani Engineering College", website: "https://tsec.edu/", location: "Mumbai, Maharashtra", exam: "MHT CET" },
    { id: 177, name: "Fr. C. Rodrigues Institute of Technology", website: "https://fcrit.ac.in/", location: "Navi Mumbai, Maharashtra", exam: "MHT CET" },
    { id: 178, name: "K. J. Somaiya College of Engineering", website: "https://kjsce.somaiya.edu/", location: "Mumbai, Maharashtra", exam: "MHT CET / JEE Main" },
    { id: 179, name: "Ramrao Adik Institute of Technology", website: "https://www.rait.ac.in/", location: "Navi Mumbai, Maharashtra", exam: "MHT CET" },
    { id: 180, name: "Shri Ramdeobaba College of Engineering and Management", website: "http://www.rknec.edu/", location: "Nagpur, Maharashtra", exam: "MHT CET" },
    { id: 181, name: "Yeshwantrao Chavan College of Engineering", website: "https://www.ycce.edu/", location: "Nagpur, Maharashtra", exam: "MHT CET" },
    { id: 182, name: "Government College of Engineering, Aurangabad", website: "https://geca.ac.in/", location: "Aurangabad, Maharashtra", exam: "MHT CET" },
    { id: 183, name: "Government College of Engineering, Amravati", website: "http://www.gcoea.ac.in/", location: "Amravati, Maharashtra", exam: "MHT CET" },
    { id: 184, name: "Shri G. S. Institute of Technology and Science", website: "http://www.sgsits.ac.in/", location: "Indore, Madhya Pradesh", exam: "JEE Main" },
    { id: 185, name: "Institute of Engineering and Technology, DAVV", website: "http://www.iet.dauniv.ac.in/", location: "Indore, Madhya Pradesh", exam: "JEE Main" },
    { id: 186, name: "Jabalpur Engineering College", website: "https://www.jecjabalpur.ac.in/", location: "Jabalpur, Madhya Pradesh", exam: "JEE Main" },
    { id: 187, name: "Madhav Institute of Technology and Science", website: "http://mitsgwalior.in/", location: "Gwalior, Madhya Pradesh", exam: "JEE Main" },
    { id: 188, name: "L.D. College of Engineering", website: "http://ldce.ac.in/", location: "Ahmedabad, Gujarat", exam: "GUJCET" },
    { id: 189, name: "Birla Vishvakarma Mahavidyalaya", website: "https://www.bvmengineering.ac.in/", location: "Anand, Gujarat", exam: "GUJCET" },
    { id: 190, name: "Dharanmsinh Desai University", website: "https://www.ddu.ac.in/", location: "Nadiad, Gujarat", exam: "GUJCET" },
    { id: 191, name: "Institute of Infrastructure Technology Research and Management (IITRAM)", website: "https://iitram.ac.in/", location: "Ahmedabad, Gujarat", exam: "JEE Main" },
    { id: 192, name: "Haldia Institute of Technology", website: "https://hithaldia.in/", location: "Haldia, West Bengal", exam: "WBJEE" },
    { id: 193, name: "Heritage Institute of Technology", website: "https://www.heritageit.edu/", location: "Kolkata, West Bengal", exam: "WBJEE" },
    { id: 194, name: "Institute of Engineering and Management (IEM)", website: "https://iem.edu.in/", location: "Kolkata, West Bengal", exam: "WBJEE" },
    { id: 195, name: "Techno Main Salt Lake", website: "https://www.technomain.tech/", location: "Kolkata, West Bengal", exam: "WBJEE" },
    { id: 196, name: "Kalyani Government Engineering College", website: "http://www.kgec.edu.in/", location: "Kalyani, West Bengal", exam: "WBJEE" },
    { id: 197, name: "Jalpaiguri Government Engineering College", website: "http://jgec.ac.in/", location: "Jalpaiguri, West Bengal", exam: "WBJEE" },
    { id: 198, name: "Cochin University of Science and Technology (CUSAT)", website: "https://cusat.ac.in/", location: "Kochi, Kerala", exam: "CUSAT CAT" },
    { id: 199, name: "Government Engineering College, Thrissur", website: "http://gectcr.ac.in/", location: "Thrissur, Kerala", exam: "KEAM" },
    { id: 200, name: "College of Engineering, Trivandrum (CET)", website: "https://www.cet.ac.in/", location: "Thiruvananthapuram, Kerala", exam: "KEAM" },

    // 201-250
    { id: 201, name: "TKM College of Engineering", website: "http://tkmce.ac.in/", location: "Kollam, Kerala", exam: "KEAM" },
    { id: 202, name: "Model Engineering College", website: "http://www.mec.ac.in/", location: "Kochi, Kerala", exam: "KEAM" },
    { id: 203, name: "Rajagiri School of Engineering & Technology", website: "https://www.rajagiritech.ac.in/", location: "Kochi, Kerala", exam: "KEAM" },
    { id: 204, name: "Veer Surendra Sai University of Technology (VSSUT)", website: "https://vssut.ac.in/", location: "Burla, Odisha", exam: "JEE Main" },
    { id: 205, name: "College of Engineering and Technology, Bhubaneswar (OUTR)", website: "https://www.cet.edu.in/", location: "Bhubaneswar, Odisha", exam: "JEE Main" },
    { id: 206, name: "Indira Gandhi Institute of Technology", website: "http://igitsarang.ac.in/", location: "Sarang, Odisha", exam: "JEE Main" },
    { id: 207, name: "Silicon Institute of Technology", website: "https://www.silicon.ac.in/", location: "Bhubaneswar, Odisha", exam: "JEE Main" },
    { id: 208, name: "CV Raman Global University", website: "https://cgu-odisha.ac.in/", location: "Bhubaneswar, Odisha", exam: "CGET" },
    { id: 209, name: "Assam Engineering College", website: "http://www.aec.ac.in/", location: "Guwahati, Assam", exam: "CEE Assam" },
    { id: 210, name: "Jorhat Engineering College", website: "https://jecassam.ac.in/", location: "Jorhat, Assam", exam: "CEE Assam" },
    { id: 211, name: "Tezpur University", website: "http://www.tezu.ernet.in/", location: "Tezpur, Assam", exam: "JEE Main" },
    { id: 212, name: "North Eastern Regional Institute of Science and Technology (NERIST)", website: "https://nerist.ac.in/", location: "Nirjuli, Arunachal Pradesh", exam: "NEE" },
    { id: 213, name: "Tripura Institute of Technology", website: "http://titagartala.ac.in/", location: "Agartala, Tripura", exam: "TBJEE" },
    { id: 214, name: "Mizoram University", website: "https://mzu.edu.in/", location: "Aizawl, Mizoram", exam: "JEE Main" },
    { id: 215, name: "Sikkim Manipal Institute of Technology", website: "https://smu.edu.in/smit.html", location: "Majitar, Sikkim", exam: "MET" },
    { id: 216, name: "Dayalbagh Educational Institute", website: "https://www.dei.ac.in/", location: "Agra, Uttar Pradesh", exam: "Academic Merit / Test" },
    { id: 217, name: "Bundelkhand Institute of Engineering & Technology", website: "https://bietjhs.ac.in/", location: "Jhansi, Uttar Pradesh", exam: "UPCET" },
    { id: 218, name: "Kamla Nehru Institute of Technology", website: "https://knit.ac.in/", location: "Sultanpur, Uttar Pradesh", exam: "UPCET" },
    { id: 219, name: "JSS Academy of Technical Education, Noida", website: "https://jssaten.ac.in/", location: "Noida, Uttar Pradesh", exam: "UPCET" },
    { id: 220, name: "Ajay Kumar Garg Engineering College", website: "https://www.akgec.ac.in/", location: "Ghaziabad, Uttar Pradesh", exam: "UPCET" },
    { id: 221, name: "KIET Group of Institutions", website: "https://www.kiet.edu/", location: "Ghaziabad, Uttar Pradesh", exam: "UPCET" },
    { id: 222, name: "ABES Engineering College", website: "https://www.abes.ac.in/", location: "Ghaziabad, Uttar Pradesh", exam: "UPCET" },
    { id: 223, name: "GL Bajaj Institute of Technology and Management", website: "https://www.glbitm.org/", location: "Greater Noida, Uttar Pradesh", exam: "UPCET" },
    { id: 224, name: "Krishna Institute of Engineering and Technology", website: "https://www.kiet.edu/", location: "Ghaziabad, Uttar Pradesh", exam: "UPCET" },
    { id: 225, name: "Noida Institute of Engineering and Technology", website: "https://www.niet.co.in/", location: "Greater Noida, Uttar Pradesh", exam: "UPCET" },
    { id: 226, name: "Guru Nanak Dev Engineering College", website: "http://gndec.ac.in/", location: "Ludhiana, Punjab", exam: "JEE Main" },
    { id: 227, name: "DAV Institute of Engineering and Technology", website: "http://www.davietjal.org/", location: "Jalandhar, Punjab", exam: "JEE Main" },
    { id: 228, name: "Punjabi University", website: "http://www.punjabiuniversity.ac.in/", location: "Patiala, Punjab", exam: "JEE Main" },
    { id: 229, name: "Chitkara University", website: "https://www.chitkara.edu.in/", location: "Rajpura, Punjab", exam: "JEE Main" },
    { id: 230, name: "DIT University", website: "https://www.dituniversity.edu.in/", location: "Dehradun, Uttarakhand", exam: "JEE Main" },
    { id: 231, name: "G.B. Pant University of Agriculture and Technology", website: "https://gbpuat.ac.in/", location: "Pantnagar, Uttarakhand", exam: "JEE Main" },
    { id: 232, name: "College of Technology, Pantnagar", website: "http://www.gbpuat.ac.in/academics/colleges/cot/index.html", location: "Pantnagar, Uttarakhand", exam: "JEE Main" },
    { id: 233, name: "Bipin Tripathi Kumaon Institute of Technology", website: "http://kecua.ac.in/", location: "Dwarahat, Uttarakhand", exam: "JEE Main" },
    { id: 234, name: "YMCA University of Science and Technology (J.C. Bose UST)", website: "https://jcboseust.ac.in/", location: "Faridabad, Haryana", exam: "JEE Main" },
    { id: 235, name: "Deenbandhu Chhotu Ram University of Science and Technology", website: "http://www.dcrustm.ac.in/", location: "Murthal, Haryana", exam: "JEE Main" },
    { id: 236, name: "University Institute of Engineering and Technology, Kurukshetra University", website: "http://www.uietkuk.org/", location: "Kurukshetra, Haryana", exam: "JEE Main" },
    { id: 237, name: "The Northcap University", website: "https://www.ncuindia.edu/", location: "Gurugram, Haryana", exam: "JEE Main" },
    { id: 238, name: "Manav Rachna International Institute of Research and Studies", website: "https://manavrachna.edu.in/", location: "Faridabad, Haryana", exam: "MRNAT / JEE Main" },
    { id: 239, name: "Sant Longowal Institute of Engineering and Technology (SLIET)", website: "http://sliet.ac.in/", location: "Sangrur, Punjab", exam: "JEE Main" },
    { id: 240, name: "National Institute of Foundry and Forge Technology (NIFFT)", website: "http://www.nifft.ac.in/", location: "Ranchi, Jharkhand", exam: "JEE Main" },
    { id: 241, name: "Ghani Khan Choudhury Institute of Engineering & Technology (GKCIET)", website: "https://www.gkciet.ac.in/", location: "Malda, West Bengal", exam: "JEE Main" },
    { id: 242, name: "Central Institute of Technology (CIT) Kokrajhar", website: "https://www.cit.ac.in/", location: "Kokrajhar, Assam", exam: "CITDEE / JEE Main" },
    { id: 243, name: "North Eastern Hill University (NEHU)", website: "https://nehu.ac.in/", location: "Shillong, Meghalaya", exam: "JEE Main" },
    { id: 244, name: "Hemvati Nandan Bahuguna Garhwal University", website: "http://hnbgu.ac.in/", location: "Srinagar, Uttarakhand", exam: "JEE Main" },
    { id: 245, name: "Gurukula Kangri Vishwavidyalaya", website: "https://www.gkv.ac.in/", location: "Haridwar, Uttarakhand", exam: "JEE Main" },
    { id: 246, name: "Shri Mata Vaishno Devi University", website: "https://www.smvdu.ac.in/", location: "Katra, J&K", exam: "JEE Main" },
    { id: 247, name: "Islamic University of Science and Technology", website: "http://www.iustlive.com/", location: "Pulwama, J&K", exam: "JEE Main" },
    { id: 248, name: "Baba Ghulam Shah Badshah University", website: "http://bgsbu.ac.in/", location: "Rajouri, J&K", exam: "JEE Main" },
    { id: 249, name: "Cluster University of Jammu", website: "https://clujammu.ac.in/", location: "Jammu, J&K", exam: "Entrance Test" },
    { id: 250, name: "Cluster University of Srinagar", website: "https://www.cusrinagar.edu.in/", location: "Srinagar, J&K", exam: "Entrance Test" },
];
